### ISSUE TITLE
Clean Chat CLI 

### ISSUE THREAD

**Issue by ivcandela** [ivcandela/simple-ai-chatbot-python#2]
right now the experience running `chatbot.py` is the following:
```
Bot Running!
hi
1/1 [==============================] - 0s 78ms/step
Good to see you again!
hello
1/1 [==============================] - 0s 19ms/step
Hello!
bye
1/1 [==============================] - 0s 19ms/step
Goodbye!
```

It can be improved through:
- the use of color
- hiding the tensorflow output
- specifying who is the user and who the bot
- whatever you can think of!

**Comment by RaulFernandezNavarro** [comment]
I'll take a look

**Comment by ivcandela** [comment]
Closing this, thanks @RaulFernandezNavarro!
